//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:09:55 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cubetech.com/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@XmlNs(namespaceURI = AuthHeader.AUTH_NS, prefix = "") })
package com.cubetech.model;

import javax.xml.bind.annotation.XmlNs;
